### ISSUE TITLE
Todo list

### ISSUE THREAD

**Issue by enpitsuLin** [enpitsuLin/uniuno#1]
<details>

<summary>

### Support Properties or Utilities

</summary>

- [x] Layout
  - [x] Aspect Ratio
  - [x] ~~Container~~
  - [x] Columns
  - [x] Break After
  - [x] Break Before
  - [x] Break Inside
  - [x] Box Decoration Break
  - [x] Box Sizing
  - [x] Display
  - [x] Floats
  - [x] Clear
  - [x] Isolation
  - [x] Object Fit
  - [x] Object Position
  - [x] Overflow
  - [x] Overscroll Behavior
  - [x] Position
  - [x] Top / Right / Bottom / Left
  - [x] Visibility
  - [x] Z-Index
- [ ] Flexbox & Grid
- [ ] Spacing
  - [x] Padding
  - [x] Margin
  - [ ] Space Between 
- [x] Sizing
  - [x] Width
  - [x] Min-Width
  - [x] Max-Width
  - [x] Height
  - [x] Min-Height
  - [x] Max-Height
- [ ] Typography
- [ ] Backgrounds
  - [x] Background Attachment
  - [x] Background Clip
  - [x] Background Color
  - [x] Background Origin
  - [x] Background Position
  - [x] Background Repeat
  - [x] Background Size
  - [x] Background Image
  - [ ] Gradient Color Stops
- [ ] Borders
  - [x] Border Radius
  - [x] Border Width
  - [x] Border Color
  - [x] Border Style
  - [ ] Divide Width
  - [ ] Divide Color
  - [ ] Divide Style
  - [x] Outline Width
  - [x] Outline Color
  - [x] Outline Style
  - [x] Outline Offset
  - [ ] Ring Width
  - [ ] Ring Color
  - [ ] Ring Offset Width
  - [ ] Ring Offset Color
- [x] Effects
  - [x] Box Shadow
  - [x] ~~Box Shadow Color~~ 
  - [x] Opacity
  - [x] Mix Blend Mode
  - [x] Background Blend Mode
- [ ] Filters
  - [x] Blur
  - [x] Brightness
  - [x] Contrast
  - [x] Drop Shadow
  - [x] Grayscale
  - [x] Hue Rotate
  - [x] Invert
  - [x] Saturate
  - [x] Speia 
  - [x] Backdrop Blur
  - [x] Backdrop Brightness
  - [x] Backdrop Contrast
  - [x] Backdrop Drop Shadow
  - [x] Backdrop Grayscale
  - [x] Backdrop Hue Rotate
  - [x] Backdrop Invert
  - [x] Backdrop Opacity
  - [x] Backdrop Saturate
  - [x] Backdrop Speia 
- [x] Tables
- [x] Transition & Animation
- [ ] Transforms
- [ ] Interactivity
- [ ] SVG
- [x] ~~A11y~~

</details>

**Comment by enpitsuLin** [comment]
some properties value which was legal value but *NOT* support in unocss (almost are static rule) so that test case will be skipped which marked with `NOT in unocss`

Maybe do some contribution to unocss make that work

**Comment by zouhangwithsweet** [comment]
Any update recently？

**Comment by enpitsuLin** [comment]
@zouhangwithsweet 🤣后面发现自己没办法说服传统派，而且自己有用不太到就没搞了， 如果大佬有兴趣可以继续搞下去我可以帮忙

***
实际上大部分常用的 CSSProperties 转 unocss 都搞定了，下面应该是处理CSS to CSSProperties 然后转换输出原子类应该 ok 了，做成 vsc 扩展感觉蛮有搞头的

**Comment by zouhangwithsweet** [comment]
我感觉挺有用的，可以发个包，我来做种子用户

**Comment by zouhangwithsweet** [comment]
社区好像有了方案🤓，不操这个心了
